DROP TABLE IF EXISTS problem CASCADE;
DROP TABLE IF EXISTS problem_hooks CASCADE;
DROP TABLE IF EXISTS grades CASCADE;

CREATE TABLE IF NOT EXISTS grades(
   grade_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
   grade    VARCHAR (20)
);

CREATE TABLE IF NOT EXISTS problem(
    problem_id     BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    creator_id     BIGINT                                              NOT NULL,
    name           VARCHAR(100)                                        NOT NULL,
    description    VARCHAR(255)                                        NOT NULL,
    grade          BIGINT                                              NOT NULL,
    rating         INTEGER,
    video_url      VARCHAR(255),
    climbs         INTEGER,
    average_grade  VARCHAR(20),
    published_date TIMESTAMP WITHOUT TIME ZONE,

    CONSTRAINT FK_PROBLEM_ON_GRADE FOREIGN KEY (grade) REFERENCES grades (grade_id)

);

CREATE TABLE IF NOT EXISTS problem_hooks(
    problem_id           BIGINT NOT NULL,
    problem_number_field VARCHAR(20)                                   NOT NULL,
    FOREIGN KEY (problem_id) REFERENCES problem(problem_id)
);



