DROP TABLE IF EXISTS track CASCADE;
DROP TABLE IF EXISTS track_hooks CASCADE;
DROP TABLE IF EXISTS grades CASCADE;


CREATE TABLE IF NOT EXISTS track
(
    track_id       BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    creator_id     BIGINT                                              NOT NULL,
    name           VARCHAR(100)                                        NOT NULL,
    description    VARCHAR(255)                                        NOT NULL,
    grade          VARCHAR(20)                                        NOT NULL,
    rating         INTEGER,
    video_url      VARCHAR(255),
    climbs         INTEGER,
    average_grade  VARCHAR(20),
    published_date TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE IF NOT EXISTS track_hooks(
    track_id           BIGINT NOT NULL,
    track_number_field VARCHAR(20)                                   NOT NULL,
    FOREIGN KEY (track_id) REFERENCES track(track_id)
);

CREATE TABLE IF NOT EXISTS grades(
    grade_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    grade VARCHAR (20)
)

